SELECT * FROM ALL_TABLES;
DROP TABLE MEMBER;
DROP TABLE POST;

SELECT * FROM POST;
SELECT * FROM MEMBER;

CREATE TABLE POST(					-- POST
	PNUM INT PRIMARY KEY,			
	TITLE VARCHAR(30),
	MID VARCHAR(10),
	CONTENT VARCHAR(1000),
	PDATE DATE DEFAULT SYSDATE
);

CREATE TABLE MEMBER(				-- MEMBER
	MID VARCHAR(10) PRIMARY KEY,
	MPW VARCHAR(15)
);

-- POST
INSERT INTO POST VALUES (1,'WELCOME','admin','WELCOME TO OUR SITE ;) ENJOY USING IT!',SYSDATE);
-- MEMBER
INSERT INTO MEMBER VALUES ('admin','1212');
INSERT INTO MEMBER VALUES ('qwe','1212');
